#Nomor 2(Program Konversi Suhu dari Celcius ke Kelvin, Reamur dan Fahrenheit)
print("Konversi Suhu dari Celcius ke Kelvin, Reamur dan Fahrenheit")
c = int(input("Masukkan Suhu dalam Celcius = "))
Kelvin = int(c + 273)
Reamur = int(c*4/5)
Fahrenheit = int((c*9/5) + 32)
print(f"Hasil Konversi dari suhu {c} derajat celcius ke Reamur adalah {Kelvin}K")
print(f"Hasil Konversi dari suhu {c} derajat celcius ke Reamur adalah {Reamur}R")
print(f"Hasil Konversi dari suhu {c} derajat celcius ke Reamur adalah {Fahrenheit}F")
